# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# Set variables once
variables:
  a: mh
  b: $(Rev:.r)
  c: $(Build.SourceVersion)
  BuildConfiguration : release

name: $(a)_$(Rev:.r)_$(Build.SourceVersion)
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    make
- script: 
    gcc -v
- script: 
    touch abc.txt
- bash: ls
- bash: echo $name
- bash: echo $(a)_$(b)_$(c) >> abc.txt
- bash: cat abc.txt


#- powershell: .\build.ps1
- powershell: gci env:* | sort-object name | Format-Table -AutoSize | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY/environment-variables.txt

- task: CopyFiles@2
  inputs:
    Contents: |
     \**\*.bin
     \**\abc.txt
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutput
- bash: ls
