# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# Set variables once
variables:
  a: mh

name: $(a)_$(Rev:.r)_$(Build.SourceVersion)
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    make
- script: 
    gcc -v
- script: 
    touch readme.txt
- bash: ls
- bash: echo $name >> readme.txt
- bash: cat readme.txt

